import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description:
    "Generated by create next app - a fully responsive and functional layout with sidebar.",
};

export default function RootLayout({ children }) {

  return (

          <SidebarProvider>
            <AppSidebar /> 
              <SidebarTrigger />
              <main role="main" className="flex-1 p-4 overflow-y-auto">
                {children}
              </main>
          </SidebarProvider>

    );
}
